**Brian Blaylock**  
**September 5, 2019**

# Notebook demonstration
This cell is a markdown cell. It is just text. It is not python code.

In [1]:
# This cell is python code. That is why 
# I need the pound sign at the begining of the line
# so Python knowns this isn't code

In [60]:
# This is almost obligatory to do...
print('Hello, world!')

Hello, world!


In [9]:
a = 8
b = a
print(a+b)

16


In [61]:
# Object introspection: 
# The question mark can be used to obtain more info on an object.
a?

Type:        int
String form: 50
Docstring:  
int([x]) -> integer
int(x, base=10) -> integer

Convert a number or string to an integer, or return 0 if no arguments
are given.  If x is a number, return x.__int__().  For floating point
numbers, this truncates towards zero.

If x is not a number or if base is given, then x must be a string,
bytes, or bytearray instance representing an integer literal in the
given base.  The literal can be preceded by '+' or '-' and be surrounded
by whitespace.  The base defaults to 10.  Valid bases are 0 and 2-36.
Base 0 means to interpret the base from the string as an integer literal.
>>> int('0b100', base=0)
4


In [62]:
# Calculate the hypotenuse of a triangle
a = 3
b = 4
c = (a**2 + b**2)**(1/2)
print('Side A: %s\nSide B: %s\nSide C: %s' % (a, b, c))

Side A: 3
Side B: 4
Side C: 5.0


# Numpy (Chapter 4.7)
Numpy, short for **numerical python**, is a python library for performing common mathematical operators on lists.

To use it, we have to import it. This is the standard way. Run the next cell.

In [11]:
import numpy as np

To use numpy functions, we can call the function `np.functionName(variableToPerformFunctionOn)`

In [16]:
a = 50

In [17]:
# Find the sine of a
np.sin(a)

-0.26237485370392877

In [20]:
# Find the square root of a
np.sqrt(a)

7.0710678118654755

In [19]:
# Exponentiate a
np.exp(a)

5.184705528587072e+21

In [24]:
# Convert degrees to radians
np.radians(90)

1.5707963267948966

In [26]:
# Conver radians to degrees
np.degrees(1.5707963267948966)

90.0

In [27]:
# Value of pi. (Notice this isn't a function performed on another object)
np.pi

3.141592653589793

In [28]:
# Special "not a number" value
np.nan

nan

## Numpy arrays are very important (Chapter 7)

Say we have a two lists of the same size and we want to add the values together for each index.

In [29]:
list_a = [1,2,3,4,5]
list_b = [5,6,7,8,9]

list_a + list_b

[1, 2, 3, 4, 5, 5, 6, 7, 8, 9]

What just happended? That isn't exactly what we wanted.

Numpy is used to do the math we want to do. We have to use the `np.array()` function to convert the list to a numpy array.

In [31]:
list_c = np.array([1,2,3,4,5])
list_d = np.array([5,6,7,8,9])

list_c + list_d

array([ 6,  8, 10, 12, 14])

That did what we wanted...the numbers were added for each index of the two arrays.

The difference is the type of the list.

In [33]:
print(type(list_a), type(list_c))

<class 'list'> <class 'numpy.ndarray'>


NOTE: Numpy arrays must be the same type. Below I have made an array that is an integer and a string. Numpy makes them both strings.

In [37]:
np.array([4, 'hi'])

array(['4', 'hi'], dtype='<U11')

You may specify the type of the data with the `dtype` argument.

In [39]:
np.array([4, '4'], dtype=float)

array([4., 4.])

## Numpy array creation (Chapter 7)

In [42]:
np.arange(1,5)

array([1, 2, 3, 4])

In [52]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [53]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

Arrays can be multi-demensional.

In [55]:
# 2D
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [59]:
# 3D
np.ones([4,4,4])

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

|Numpy Function| Use|
|--|--|
|`np.sum()`| Sum all numbers in a list/array.
|`np.sin()`, `np.cos()`, `np.tan()`| Trig functions
|`np.max()`, `np.min()`| Find max or min value in list/array
|`np.mean()`, `np.median()`| Find mean or median value in list/array
|`np.sqrt()`| Square Root the values
|`np.shape()`|Return the shape of an array|
|`np.zeros([n,n])`|An array of zeros with size nxn|
|`np.ones([n,n])`|An array of ones with size nxn|
|`np.linspace(start, end, n)`|Array of evenly spaced numbers between start and end|
|`np.range(start, end, step)`|Range of numbers|
|...|...|

Note: If you give the numpy function a list, it will convert it to a numpy array for you, e.g., `np.array([1,2,3,4])`

Other useful values
- `np.pi` is the value of pi.
- `np.nan` stands for not a number.

# Flow control (Chapter 5)
Python is very picky on how code is indented. This syntax is used to keep code relatively clean. **Pay attention to the indentation in these examples**.

## For Loop
`for`: executes a block of code for all items in an iterable object (string, list, tuple, array, etc.).

For loop syntax:

    for [variable to iterate] in [sequence]:
        [do this code]

[Reference: For Loop](https://www.tutorialspoint.com/python3/python_for_loop.htm)

In [127]:
for i in 'Go Utes':
    print("Give me a...", i)
print("What does that spell?!")

Give me a... G
Give me a... o
Give me a...  
Give me a... U
Give me a... t
Give me a... e
Give me a... s
What does that spell?!


In [128]:
for i in ['apple', 'banana', 'orange']:
    print("Fruit:", i)

Fruit: apple
Fruit: banana
Fruit: orange


**What did that do?**

In [66]:
myList = [3,[4,4,5],4,'Utah']
for i in myList:
    print(i)

3
[4, 4, 5]
4
Utah


## While Loop
`while`: execute a block of code as long as a condition is met.  

> WARNING: Beware of infinite loops.

While loop syntax:

    while [condition to check]:
        [code block]

[Reference: While Loop](https://www.tutorialspoint.com/python3/python_while_loop.htm)

In [67]:
z = 0
while z < 5:
    z = z + 1
    print(z)

print('while loop finished')

1
2
3
4
5
while loop finished


<br><br><br>
Let's do something more interesting.

# Convert Temperature Units

In [68]:
# Compute the conversion of Celsius to Farhenheit for the range of values 
# between -20 and 40 C at 5 C intervals


print ('C   \t    F')      # \t is a tab
print ('-------------------')

# assign value to variable c for Celsius
c = -20

# assign an increment, dc (delta celsius), to add to the values of c
dc = 4

# Use a while loop to determine the value of the temperature
# in F for each whole degree C as long as C is less than 40.
while c <= 40:
    f = (9/5)*c+32            # convertion
    print (c, '\t', f)        # print value of c and f
    c = c + dc                # increment c by dc
    
print ('-------------------')

C   	    F
-------------------
-20 	 -4.0
-16 	 3.1999999999999993
-12 	 10.399999999999999
-8 	 17.6
-4 	 24.8
0 	 32.0
4 	 39.2
8 	 46.4
12 	 53.6
16 	 60.8
20 	 68.0
24 	 75.2
28 	 82.4
32 	 89.6
36 	 96.8
40 	 104.0
-------------------


> **What just happened?**  
- Do you understand how the while loop works?  
- Why were each of these values printed? 
- What made the loop stop?

Now do the same but with cleaner printing using string modulus...(it is your responsiblity to look in the text book how to do this).

In [69]:
print ('---------')

#initialize first value of c
c = -20.

#define the increment, dc, to add to the values of c
dc = 4.

#determine the value of the temperature in F for each whole degree C
while c <= 40: 
    f = (9./5.)*c+32.
    print ("%6.1f C = %6.1f F" % (c,f)) 
    c = c + dc 
    
print ('---------')

---------
 -20.0 C =   -4.0 F
 -16.0 C =    3.2 F
 -12.0 C =   10.4 F
  -8.0 C =   17.6 F
  -4.0 C =   24.8 F
   0.0 C =   32.0 F
   4.0 C =   39.2 F
   8.0 C =   46.4 F
  12.0 C =   53.6 F
  16.0 C =   60.8 F
  20.0 C =   68.0 F
  24.0 C =   75.2 F
  28.0 C =   82.4 F
  32.0 C =   89.6 F
  36.0 C =   96.8 F
  40.0 C =  104.0 F
---------


# Practice
- Write a Python loop that sums all the numbers in a list.
- Write a Python loop that finds the smallest value of a list.

In [7]:
# Create a list of numbers


In [8]:
# Make a place holder variable to sum the values
total = 0

In [71]:
# Write a for loop that loops over each item of the list and adds it to the total


## Assignment #2 😁
### Read and work through chapter 5 and 7.1-7.16 in the textbook. (skip 5.4)

1. Do this in a new notebook called `uXXXXXX_assignment2.ipynb`
1. Label each section with a comment or markdown (examples follow)
1. **If a certian function or statement doesn't make sense to you, ask a questions on "Teams".**
1. Upload the notebook to canvas.
1. Assignment is Due September 13th (Friday, bad luck).

What I'm looking for is that you have completed the examples from the book. But you won't learn anything new if you just type the commands. Pay attention to the syntax and the output.

> ## **In 5.1 and other sections, instead of `raw_input()`, use `input()`.**
`raw_input` is for python2. `input` is for python3

In [75]:
s = input('hello there. Give me a number...')

hello there. Give me a number... 4


In [77]:
# Notice that the value of s is a string.
s

'4'

In [78]:
s = float(s)

In [80]:
# Now s is a float.
s

4.0

# Example:

In [83]:
# 7.4.1

a = np.zeros((2,3), dtype=np.float_)

In [84]:
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [86]:
b = np.ones((3,4), dtype=np.float_)

In [87]:
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [90]:
# 7.4.2

a = np.array([[2,3,4], [5,6,7]])
a

array([[2, 3, 4],
       [5, 6, 7]])

In [92]:
b = np.zeros_like(a)

In [93]:
b

array([[0, 0, 0],
       [0, 0, 0]])

In [95]:
# 7.4.3
d = np.empty((2,3), dtype=np.float_)

In [96]:
d

array([[0., 0., 0.],
       [0., 0., 0.]])

You can also use markdown to label the sections...

# 7.5

## 7.5.1

In [97]:
a = np.arange(0,11,2)

In [98]:
a

array([ 0,  2,  4,  6,  8, 10])

In [100]:
b = np.arange(10, -1, -3)

In [101]:
b

array([10,  7,  4,  1])

In [102]:
c = np.arange(0.0, 1.0, 0.2)

In [103]:
c

array([0. , 0.2, 0.4, 0.6, 0.8])

**Sometimes you might need to create your own array, like in 7.6.2** Pay attention to the brackets

In [105]:
# 7.6.2

a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

In [106]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [107]:
a[0,0]

1

In [108]:
a[2,0]

7

In [109]:
a[0,2]

3

In [110]:
a[0:, 2]

array([3, 6, 9])

In [111]:
a[2, :]

array([7, 8, 9])